#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'aozora-polly'
require 'open-uri'
require 'pry'

if ARGV.size == 0
  puts "#$0 url mp3"
  exit
end

aozora_url, mp3_path = ARGV

AozoraPolly.url2mp3(aozora_url, mp3_path)
puts "Generated: #{mp3_path}"
