#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require 'aozora-polly'
require 'open-uri'
require 'pry'

if ARGV.size == 0
  puts "#$0 url ssml"
  exit
end

aozora_url, ssml_path = ARGV

ssml = AozoraPolly.url2ssml(aozora_url)
File.write(ssml_path, ssml)
puts "Generated: #{ssml_path}"
